# Generated by Django 4.0.4 on 2022-05-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recent_ann',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='', max_length=25)),
                ('title', models.CharField(default='', max_length=100)),
                ('content', models.TextField(blank=True)),
                ('link', models.TextField(blank=True)),
            ],
        ),
    ]
